export enum WhatsAppConnectionStatus {
  INITIALIZING = "INITIALIZING",
  QR_CODE_GENERATED = "QR_CODE_GENERATED",
  AUTHENTICATING = "AUTHENTICATING",
  READY = "READY",
  DISCONNECTED = "DISCONNECTED",
  CLOSED = "CLOSED",
  ERROR = "ERROR",
}
