import Header from "@/components/landing_page/Header";
import Hero from "@/components/landing_page/Hero";
import Benefits from "@/components/landing_page/Benefits";
import Collaboration from "@/components/landing_page/Collaboration";
import Pricing from "@/components/landing_page/Pricing";
import Footer from "@/components/landing_page/Footer";
import { Metadata } from "next";
import { getPlans } from "@/services/api/subscriptionPlans";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Home() {
  const response = await getPlans();
  return (
    <>
      <div className="pt-[4.75rem] lg:pt-[5.25rem] bg-white w-screen overflow-x-hidden">
        <Header />
        <Hero />
        <Benefits />
        <Collaboration />
        {/* <Services /> */}
        <Pricing pricingList={response.data} />
        {/* <Roadmap /> */}
        <Footer />
      </div>
      {/* <ButtonGradient /> */}
    </>
  );
}
